### PR TITLE
add support for unix socket transport

### PR DESCRIPTION
**Pull request by olivier-matz-6wind**
In addition to SSH and TLS transport, add the support for UNIX
socket.
Related with this pull request in libnetconf2: https://github.com/CESNET/libnetconf2/pull/123

This pull request contains one patch for the server and one for the cli.

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
seems the tests are not passing, can you please take a look?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Olivier,
I have restarted the tests after I merged your other pull request, it ran with it already but the tests crashed.

Regards,
Michal

**Comment by olivier-matz-6wind** [comment]
oh ok, sorry, I will have a look, thanks

**Comment by michalvasko** [comment]
Hi,
right, I could have warned you about that, sorry.

Regards,
Michal

**Pull request merged**
