### PR TITLE
cli: make the CLI prompt configurable

### PR DESCRIPTION
**Pull request by hthiery**

### CODE REVIEW

**Review by michalvasko — CHANGES_REQUESTED** [review]
Okay, if you find it useful for some reason, but please reorganize the files a bit. No reason for there to be more configurable files, so you can just merge `cli_version.h.in` and `cli_prompt.h.in` to `cli_config.h.in`. Also, please call the macro `NC_CLI_PROMPT` since it is no longer local and it was a bad name anyway.

**Comment by hthiery** [comment]
> Okay, if you find it useful for some reason, but please reorganize the files a bit. No reason for there to be more configurable files, so you can just merge `cli_version.h.in` and `cli_prompt.h.in` to `cli_config.h.in`. Also, please call the macro `NC_CLI_PROMPT` since it is no longer local and it was a bad name anyway.

What do you mean with "call the macro `NC_CLI_PROMPT`"?
- Do you mean I should change the cmake config option to NC_CLI_PROMPT?
- or change the name PROMPT to NC_CLI_PROMPT?

**Comment by michalvasko** [comment]
I meant the macro `PROMPT` to be called `NC_CLI_PROMPT`. CMake var `CLI_PROMPT` can stay as it is.

**Review by michalvasko — APPROVED** [review]

**Comment by hthiery** [comment]
indeed .. I used master :-/

**Review by michalvasko — APPROVED** [review]

**Pull request merged**
