### PR TITLE
close memory leak (test case + solution)

### PR DESCRIPTION
**Pull request by frimpler**
A memory leak reg. nc-poll-sessions has been detected during shutting down netopeer2-server. This PR provides test case and solution.

Regards,
Frank

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
seems fine but with regards to the last changes, please also use the provided `ATOMIC_UINT32_T` for your counter as it is set/accessed from several threads. Thanks.

Regards,
Michal

**Comment by frimpler** [comment]
Please have a look, again - hope, that's ok that way.

**Comment by michalvasko** [comment]
Hi Frank,
I have changed those atomic macros a bit, again. To compile, you only need to rename `ATOMIC_UINT32_T` to just `ATOMIC_T`. However, please also use `ATOMIC_LOAD` and `ATOMIC_STORE` wherever needed. Thanks.

Regards,
Michal

**Comment by frimpler** [comment]
adapted it...

**Comment by michalvasko** [comment]
Hi Frank,
okay, thanks.

Regards,
Michal

**Pull request merged**
